# Generated by Django 4.0 on 2021-12-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
    ]
