# Generated by Django 4.0 on 2021-12-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0002_contactspagecontent_partnerspagecontent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequsitestPageContent',
            new_name='RequsitesPageContent',
        ),
    ]
