# Generated by Django 4.0 on 2021-12-11 07:31

from django.db import migrations, models
import django.db.models.deletion
import maincontent.models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0004_alter_contactspagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=300)),
                ('picture', models.ImageField(upload_to=maincontent.models.image_folder)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincontent.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincontent.category', to_field='name')),
            ],
        ),
    ]
