# Generated by Django 4.0 on 2021-12-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0005_brand_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'марку товара', 'verbose_name_plural': '2.Марки товаров'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': '1.Категории продукции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукцию', 'verbose_name_plural': '3.Продукция'},
        ),
    ]
